# pull in elixir 1.17.2-otp-27
services:
  db:
    image: postgres:16
    environment: &db_env
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  test:
    build: .
    volumes:
      - .:/mnt
    environment: 
      <<: *db_env
      POSTGRES_HOST: db
      MIX_ENV: test
    depends_on:
      - db